### PR TITLE
refactor(helix-org): delete Position from domain and code

### PR DESCRIPTION
**Pull request by philwinder**
## Summary
- **Delete the Position concept** from helix-org's domain, persistence, application, REST/MCP and frontend surfaces. Workers now hold `RoleID` and `ParentID` (Worker → Worker) directly.
- **Subscriptions move from position-anchored to worker-anchored** `(org, worker, stream)`. They die on `fire_worker`; the hiring playbook prompt re-subscribes new hires explicitly. This unblocks specialisation (two workers in the same role can read disjoint streams) and load patterns (only the on-call worker subscribes).
- **Chart UI** is replaced by a simple workers-grouped-by-Role overview. The old ReactFlow position-tree canvas is gone.

## Why
The Position layer added complexity that did not earn its keep:
- Position-anchored subscriptions forced *every* worker in a slot to receive *every* event — blocking load patterns and per-worker specialisation.
- `create_position` + `hire_worker` was a two-step dance for a single conceptual action.
- The chart UI carried hundreds of lines of ReactFlow + dagre + drag-to-subscribe state for a concept the user wanted to demote.
- Reporting + role binding both collapse onto Worker cleanly.

## Decisions baked in (locked in via plan)
| Question | Decision |
|---|---|
| Subscription anchor | **Worker** — `(org, worker, stream)`, die on fire |
| Reporting hierarchy | `Worker.parent_id` → Worker; `w-owner` has nil parent |
| Chart UI | Drop tree, group Workers by Role |
| Migration | Wipe `org_*` tables (helix-org is pre-release) |

## Test plan
- [x] Backend: `CGO_ENABLED=0 go build ./api/... && go vet ./api/pkg/org/...` pass
- [ ] CI: full Drone pipeline including `go test` and frontend build (this PR)
- [ ] Inner-helix end-to-end smoke (after CI green):
  - Register `test@helix.ml` / `helixtest`, complete onboarding
  - Confirm only `w-owner` exists with `role_id=r-owner`, `parent_id=NULL`, no `org_positions` table
  - In `/ui/chat`, hire an AI editor that reads `drafts` — validate Role + Worker (role_id + parent_id=w-owner) + Stream + Subscription
  - Fire the editor → row + subscription gone; publish to drafts → no activation
  - Re-hire → re-subscribe → publish → new worker activates
  - Specialisation: 2 `r-code-reviewer` workers subscribed to different streams; only the matching worker activates per event

## Key files
- Domain: `api/pkg/org/domain/orgchart/{worker,ids,role}.go` (Position deleted)
- Persistence: `api/pkg/org/infrastructure/persistence/gorm/{worker,subscription,gorm}.go`; new migration `0004_drop_org_positions.up.sql`
- Tools: deleted `create_position.go`, `read_positions.go`; rewired `hire_worker`, `subscribe`, `unsubscribe`, `stream_members`, `dm`, `invite_workers`, `worker_log`, `read_events`, `activation_stream`, `update_role`
- Lifecycle: `DeletePosition` dropped; `Fire` cascades worker's subscriptions; `DeleteRole` fires workers with that role
- Dispatcher: subscriptions resolve directly to worker
- Bootstrap: drop `p-root`; w-owner created with role_id=r-owner, parent_id=nil
- REST API: drop `/positions/*`; replace `/chart` with `/overview` (workers grouped by role); new `/workers/{id}/subscriptions`
- Frontend: drop position hooks/types; new `useHelixOrgOverview` + `use{List,Subscribe,Unsubscribe}Worker`; HelixOrgChart replaced with role-grouping overview; worker-detail SubscriptionsPanel becomes worker-anchored; copy updated everywhere
- QA.md rewritten

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by lukemarsden** [comment]
## QA review — feat/delete-positions-from-org (8e34a60)

### Unit tests: FAIL ❌

`go test ./api/pkg/org/...` on 8e34a60:

| Package | Result |
|---------|--------|
| `api/pkg/org/interfaces/server/api` | ✅ PASS |
| `api/pkg/org/interfaces/server` | ❌ FAIL — 6 tests |
| All other `api/pkg/org/...` packages | ✅ PASS |

**Failing tests** (all 6 are MCP endpoint tests):
```
--- FAIL: TestMCPListToolsFromRole
--- FAIL: TestMCPListTools
--- FAIL: TestMCPUngrantedToolHidden
--- FAIL: TestMCPListPromptsVisibleWithGrant
--- FAIL: TestMCPListPromptsHiddenWithoutGrant
--- FAIL: TestMCPInvokePing
--- FAIL: TestMCPGetPromptReturnsSeedMessages
```

**Root cause** — copy-paste error in `server_test.go`. Both `newTestServer` and `newTestServerRoleDerived` seed a role named `r-ceo` but then create the worker with `r-owner`:
```go
// line ~50 and ~99: both functions contain this bug
ai, _ := orgchart.NewAIWorker("w-ceo", "r-owner", nil, "", "org-test")
//                                        ^^^^^^^^ should be "r-ceo"
```
Since `r-owner` is not seeded in the test DB, `buildMCPServer` fails on `s.store.Roles.Get(..., "r-owner")` → returns nil → SDK responds 400 Bad Request → all MCP tests fail at connection.

**Fix**: change `"r-owner"` → `"r-ceo"` in both `NewAIWorker` calls in `server_test.go`.

---

### QA.md (new plan): LGTM ✅

The rewritten QA.md is consistent with the domain changes — Worker-anchored subscriptions, `r-owner.tools.length == 21`, no `org_positions` table, §8 specialisation test case. New plan reads clearly.

---

### Migration number note

This PR introduces `0004_drop_org_positions.up.sql`. Issue #2524 (strip grant tools from `org_roles.tools`) previously noted `0004_remove_grant_tools_from_roles` as the next migration — **that fix now needs to be `0005`**. Will update #2524.

---

### Drone CI

Build 1873 is running — result pending. Based on the MCP test failures above, expect it to fail in the `default` pipeline once it reaches the `api/pkg/org/interfaces/server` package.

**Comment by lukemarsden** [comment]
## QA pre-merge unit test analysis — commit 8e34a60

Ran \`go test ./api/pkg/org/...\` on **8e34a60** (feat/delete-positions-from-org). Two packages have failing tests — missed test updates from the position→worker refactor.

---

### FAIL 1 — \`api/pkg/org/application/tools\` (3 tests)

**TestHireWorkerAICreatesActivationStreamAndDispatches** (`hire_worker_test.go:231`)

Assertion still checks a _position_-anchored subscription:
```go
deps.Store.Subscriptions.Find(ctx, "org-test", "p-root", streamID)
```
New model is worker-anchored. Should check the caller's worker ID (e.g. `"w-owner"` or whatever `caller.ID()` is), not `"p-root"`. Same for the "must NOT be subscribed" check at line 234 which uses `orgchart.WorkerID("p-eng")`.

**TestUpdateRoleAndIdentityAreDomainWrites** (`builtins_test.go:220`)

`hire_worker` called with the old `positionId` parameter:
```go
invokeExpectID(t, ownerSession, tools.HireWorkerName, map[string]any{
    "id": "w-a", "positionId": "p-eng-a", "kind": "ai",
    "identityContent": "# Alice",
})
```
New `hire_worker` requires `roleId`. Error: `"roleId is required"`.

**TestDM** (`builtins_test.go:488`)

Alice and Bob are seeded with `role_id = "r-member"` but only `"r-owner"` role is created in the test store. `buildMCPServer` can't resolve `r-member` → returns nil → `400 Bad Request` on MCP initialize.

---

### FAIL 2 — \`api/pkg/org/interfaces/server\` (7 tests — all same root cause)

`TestMCPListTools`, `TestMCPListPromptsHiddenWithoutGrant`, `TestMCPInvokePing`, `TestMCPListPromptsVisibleWithGrant`, `TestMCPGetPromptReturnsSeedMessages`, `TestMCPListToolsFromRole`, `TestMCPUngrantedToolHidden`

All fail because `newTestServer` / `newTestServerRoleDerived` seed role `"r-ceo"` but create worker `w-ceo` with `role_id = "r-owner"`:
```go
role, _ := orgchart.NewRole("r-ceo", ...)   // seeded role
ai, _ := orgchart.NewAIWorker("w-ceo", "r-owner", nil, "", "org-test")  // wrong role_id
```
`buildMCPServer` does `store.Roles.Get(ctx, orgID, "r-owner")` → not found → returns nil → `400 Bad Request`.

Fix: change `"r-owner"` to `"r-ceo"` (the role that was actually seeded) in `newTestServer` and `newTestServerRoleDerived`.

---

**All other packages pass.** These are test-only misses — no production code is broken by these failures, but they'll block the Drone CI run.

**Comment by lukemarsden** [comment]
**QA follow-up — bee485aa fix confirmed ✓**

Commit bee485aa addresses all four test failures from my prior review. Local verification:

```
CGO_ENABLED=0 go test ./api/pkg/org/... -count=1
```

All **24 packages PASS** including `api/pkg/org/interfaces/server` (the 7 MCP tests that were failing with 400 Bad Request).

**Changes verified:**
- `server_test.go`: both `NewAIWorker` calls now pass `"r-ceo"` (lines 50 + 103) — matches the role actually seeded in the test DB. `buildMCPServer` role lookup succeeds; MCP tests pass.
- `builtins_test.go`: `hire_worker` payload switched to `roleId`/`parentId` schema; TestDM uses `r-member` (an actually-created role, not the phantom `r-owner` reference).
- `hire_worker_test.go`: subscription assertion flipped from `p-root` to `w-owner` — correct under worker-anchored model.
- `0004_drop_org_positions.up.sql`: extended to also drop `org_roles`, `org_streams`, `org_events`, `org_environments`, `org_runtime_state`, `org_activations`, `org_configs` so existing dev DBs re-bootstrap cleanly without "already exists" conflicts.

**Drone build 1874** is running on bee485aa — no blocking issues found in code. Watching for CI result.

**Comment by lukemarsden** [comment]
**QA — build-frontend TypeScript failure on bee485aa**

Drone build 1874 fails on the `build-frontend` step (`npx tsc --noEmit`). Root cause: one new TypeScript error introduced by the position-removal frontend rewrite in commit 8e34a60.

```
src/pages/HelixOrgChart.tsx(43,11): error TS2322:
Type '{ children: Element; topbarTitle: string; }' is not assignable to type
'IntrinsicAttributes & { topbarContent?: ReactNode; ... breadcrumbTitle?: string; ... }'.
```

**Root cause**: `HelixOrgChart.tsx:43` passes `topbarTitle="Overview"` to `<Page>`, but `topbarTitle` is not a valid prop on `Page`. Every other HelixOrg page uses `breadcrumbTitle`:
- `HelixOrgWorkers.tsx`: `breadcrumbTitle="Workers"`
- `HelixOrgRoles.tsx`: `breadcrumbTitle="Roles"`
- `HelixOrgRoleDetail.tsx`: `breadcrumbTitle={roleId ?? 'Role'}`

**Fix** (one character change, line 43 of `HelixOrgChart.tsx`):
```diff
-    <Page topbarTitle="Overview">
+    <Page breadcrumbTitle="Overview">
```

This is the only error introduced by PR #2527 vs main. The remaining TypeScript errors visible from my local npm install are a local artifact (different MUI package resolution vs yarn --frozen-lockfile) — they do not appear on Drone builds of main-branch commits.

Go unit tests remain green (24/24 on bee485aa). This is the last thing blocking CI.

**Comment by lukemarsden** [comment]
**QA — Drone build #1874 failure root cause identified and fixed (e990671)**

Drone build 1874 on `bee485aa` failed in the `build-frontend` step due to a TypeScript type error — not the Go tests (which all pass):

```
src/pages/HelixOrgChart.tsx(43,11): error TS2322:
  Type '{ children: Element; topbarTitle: string; }' is not assignable to type '...'
  Property 'topbarTitle' does not exist on type ...
```

`HelixOrgChart.tsx` was passing `topbarTitle="Overview"` to `<Page>`, but that prop does not exist — the correct prop is `breadcrumbTitle`. All other new pages in this PR (`HelixOrgRoles`, `HelixOrgWorkers`, `HelixOrgRoleDetail`, `HelixOrgWorkerDetail`) use `breadcrumbTitle` correctly.

**Fix:** Changed `topbarTitle` → `breadcrumbTitle` in `HelixOrgChart.tsx` line 43. Verified `npx tsc --noEmit` clean after the change. Pushed as commit `e990671`.

Go tests (`CGO_ENABLED=0 go test ./api/pkg/org/... -count=1`) remain all 24 packages PASS on this commit.

**Comment by lukemarsden** [comment]
**QA — e9906715 fix confirmed ✓**

`breadcrumbTitle="Overview"` at `HelixOrgChart.tsx:43` — correct. TypeScript error count is back to baseline (matches main). Drone build should now pass `npx tsc --noEmit`.

Watching for CI result on build 1875.

**Comment by lukemarsden** [comment]
**QA CI green — e99067157c ✓**

All issues resolved. Drone build [1875](https://drone.lukemarsden.net/helixml/helix/1875) on **e99067157c** is **passing**.

**Fix chain summary:**

| Commit | Issue | Fix |
|--------|-------|-----|
| `bee485aa` | Go unit tests (10 failures, 2 packages) | Corrected worker-anchored subscription assertions, switched `positionId→roleId`, seeded correct role IDs in test stores |
| `e99067157c` | `tsc --noEmit` CI failure | `topbarTitle` → `breadcrumbTitle` in `HelixOrgChart.tsx` (invalid prop on `Page` component) |

**Current state:**
- `go test ./api/pkg/org/...` — 24 packages PASS ✓
- `npx tsc --noEmit` — no errors ✓
- Drone build 1875 — **passing** ✓

No blocking issues. Ready for review and merge.
